# Question 1 

In [20]:
import numpy as np
new_array=np.random.randint(2,19,size=(1,9))
print(new_array)
print(type(new_array))
my_list=new_array.tolist()
print(my_list)
print(type(my_list))

[[17  8  4  3  5  2  7  8 14]]
<class 'numpy.ndarray'>
[[17, 8, 4, 3, 5, 2, 7, 8, 14]]
<class 'list'>


# Question 2

In [114]:
new_array=np.random.randint(2,5,size=(2,3))
print(new_array)
#Methode 1
diag=np.diagonal(new_array)
print('la somme des element diagonal est =',sum(diag))
#Methode 2
result =  np.trace(new_array)
print('la somme des element diagonal est =',result)


[[2 4 2]
 [4 4 3]]
la somme des element diagonal est = 6
la somme des element diagonal est = 6


# Question 3 :


In [132]:
import numpy as np
new_array=np.random.randint(1,10,size=(2,3))
print('\n',new_array)
x=3
h_list=[]
rows=new_array.shape[0]
cols=new_array.shape[1]
for i in range(0,rows):
    for j in range(0,cols):
        if (new_array[i,j]>x):
            h_list.append(new_array[i,j])
        else:
            h_list=h_list
print('\nThe value higher than x=%d are %s :' % (x,h_list))


 [[5 9 8]
 [5 2 6]]

The value higher than x=3 are [5, 9, 8, 5, 6] :


# Question 4 : 

In [112]:
import numpy as np
A=np.random.randint(1,10,size=(2,3))
print('\nA=',A,'\n')
B=np.random.randint(2,19,size=(2,3))
print('\nB=',B,'\n')
C=A+B
print('C=',C)



A= [[1 7 3]
 [3 8 3]] 


B= [[11 10  5]
 [17 10  8]] 

C= [[12 17  8]
 [20 18 11]]


# Question 5 : 

In [113]:
import numpy as np
A=np.random.randint(1,10,size=(5,5))
print('\nA=',A,'\n')
print("\n Substract the mean of each row of the given matrix:\n")
Y =A-A.mean( axis=1 , keepdims=True )
print(Y)


A= [[1 1 9 2 3]
 [7 2 4 9 8]
 [7 9 1 3 1]
 [7 5 2 3 7]
 [6 1 3 8 5]] 


 Substract the mean of each row of the given matrix:

[[-2.2 -2.2  5.8 -1.2 -0.2]
 [ 1.  -4.  -2.   3.   2. ]
 [ 2.8  4.8 -3.2 -1.2 -3.2]
 [ 2.2  0.2 -2.8 -1.8  2.2]
 [ 1.4 -3.6 -1.6  3.4  0.4]]
